- hosts: localhost

  tasks:
    - name: Install snaps with classic confinement
      become: true
      community.general.snap:
        name: "{{ item }}"
        classic: true
      loop:
        # https://code.visualstudio.com/download
        # https://snapcraft.io/code
        - code
        # https://ghostty.org/docs/install/binary#snap
        # https://snapcraft.io/ghostty
        - ghostty

    - name: Install snaps
      become: true
      community.general.snap:
        name:
          # https://www.spotify.com/pt-en/download/linux/
          # https://snapcraft.io/spotify
          - spotify
          # https://snapcraft.io/steam
          - steam
